export { default as Home } from "./Home/home";
export { default as HomeHeader } from "./Home/HomeHeader/homeHeader";
export { default as FoodCategory } from "./Home/FoodCategory/foodCategory";
export { default as FoodCategoryHeader } from "./Home/FoodCategory/FoodCategoryHeader/foodCategoryHeader";
export { default as MainFood } from "./Home/FoodCategory/MainFood/mainFood";
export { default as Menu } from "./Home/FoodCategory/Menu/menu";
export { default as CategoryPage } from "./CategoryPage/CategoryPage";
export { default as Supplement } from "./Home/Supplement/supplement";
export { default as LandingPage } from "./LandingPage/LandingPages";
